#!/bin/bash
CONTAINER_NAME="docker-pipeline"
IMAGE_URI=$(cat /home/ec2-user/app/imagedefinitions.json | jq -r '.[0].imageUri')

# Stop existing container
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 339712798271.dkr.ecr.us-west-2.amazonaws.com
docker stop $CONTAINER_NAME || true
docker rm $CONTAINER_NAME || true

# Run new container
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 339712798271.dkr.ecr.us-west-2.amazonaws.com
docker pull $IMAGE_URI
docker run -d --name $CONTAINER_NAME -p 80:80 $IMAGE_URI
