#!/bin/bash
CONTAINER_NAME="docker-pipeline"
IMAGE_URI=$(cat /home/ec2-user/app/imagedefinitions.json | jq -r '.[0].imageUri')

# Stop existing container
docker stop $CONTAINER_NAME || true
docker rm $CONTAINER_NAME || true

# Run new container
docker pull $IMAGE_URI
docker run -d --name $CONTAINER_NAME -p 80:80 $IMAGE_URI
